import { Geist_Mono, Noto_Sans, Noto_Sans_JP } from 'next/font/google';

import { UserLayout } from '@/components';
import LoadingFullPage from '@/components/user/layouts/LoadingFullPage';
import { getMessages } from '@/i18n';
import { getRequestLocale } from '@/i18n/request';

import { App as AntdApp, ConfigProvider, theme as antdTheme } from 'antd';
import 'antd/dist/reset.css';
import enUS from 'antd/locale/en_US';
import viVN from 'antd/locale/vi_VN';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';

import './globals.css';

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin', 'vietnamese'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

const notoSansJP = Noto_Sans_JP({
  variable: '--font-noto-sans-jp',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getRequestLocale();
  const messages = getMessages(locale);
  const antdLocale = locale === 'vi' ? viVN : enUS;
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${notoSansJP.variable} ${geistMono.variable} antialiased`}
      >
        <LoadingFullPage />
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ConfigProvider locale={antdLocale} theme={{ algorithm: antdTheme.defaultAlgorithm }}>
            <AntdApp>
              <UserLayout>{children}</UserLayout>
            </AntdApp>
          </ConfigProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
