import { Geist, Geist_Mono } from 'next/font/google';

import { getMessages } from '@/i18n';
import { getRequestLocale } from '@/i18n/request';

import { App as AntdApp, ConfigProvider, theme as antdTheme } from 'antd';
import 'antd/dist/reset.css';
import enUS from 'antd/locale/en_US';
import viVN from 'antd/locale/vi_VN';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getRequestLocale();
  const messages = getMessages(locale);
  const antdLocale = locale === 'vi' ? viVN : enUS;
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ConfigProvider locale={antdLocale} theme={{ algorithm: antdTheme.defaultAlgorithm }}>
            <AntdApp>{children}</AntdApp>
          </ConfigProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
